# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170525_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='time_stamp',
        ),
    ]
